services:

  # synapse:
  #   image: matrixdotorg/synapse:v1.110.0
  #   environment:
  #     - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
  #   volumes:
  #     - ./volumes/synapse:/data/
  #   ports:
  #     - 8008:8008
  #   depends_on:
  #     - postgres

  menuflow:
    image: ikonoim/menuflow:latest
    restart: unless-stopped
    # Only use this if you want to develop in this project
    # build: .
    ports:
      - 29400:29400
    depends_on:
      - postgres
    # Only use this if you want to develop in this project
    # entrypoint: ./run.sh dev
    volumes:
      # Only use this if you want to develop in this project
      # - .:/opt/menuflow
      - ./volumes/menuflow:/data
      - ./volumes/menuflow/flows:/data/flows

  postgres:
    image: postgres:14-alpine
    restart: unless-stopped
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: menuflow
      POSTGRES_PASSWORD: secretfoo
      POSTGRES_DB: menuflow
      POSTGRES_INITDB_ARGS: --encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - ./volumes/schemas:/var/lib/postgresql/data
